builds:
  - id: darwin-amd64
    main: ./
    binary: gckd-darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: linux-amd64
    main: ./
    binary: gckd-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
      - CGO_CFLAGS=--sysroot=/sysroot/linux/amd64
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/amd64
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/lib/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - id: golang-cross
    builds:
      - darwin-amd64
      - linux-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: kalfonso
    name: gorelease-kafka-demo
  prerelease: auto
  draft: false