name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  deployable:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: ./bin/hermit env --raw >> $GITHUB_ENV
      - name: Build Demo
        run: |
          make GOOS=linux GOARCH=amd64 CHANNEL=stable build
          make GOOS=darwin GOARCH=amd64 CHANNEL=stable build
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}